baseURL = 'https://ariel-os.org/'
languageCode = 'en-us'
title = 'Ariel OS'
theme = 'ariel-os'

disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[menus]
  [[menus.main]]
    name = 'Learn'
    url = 'https://ariel-os.github.io/ariel-os/dev/docs/book/'
    weight = 10

  [[menus.main]]
    name = 'API Reference'
    url = 'https://ariel-os.github.io/ariel-os/dev/docs/api/'
    weight = 20

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 30

  [[menus.main]]
    name = 'Repo'
    url = 'https://github.com/ariel-os/ariel-os'
    weight = 40

[markup]
  [markup.highlight]
    style = "bw"

[params]
  title='Ariel OS'
  description='A library operating system for secure, memory-safe, low-power IoT, built on Rust from the ground up'
  images = ['favicons/android-512.png']
