name: Look at how GitHub thinks DNS works

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: dig
        run: |
          set -x
          dig A ariel-os.org
          dig AAAA ariel-os.org
          dig SOA ariel-os.org
